[package]
name = "AoC-14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
dirs = "4.0.0"
image = "0.24.5"
nom = "7.1.1"
